// Curated word lists for room code generation.
// ~60 adjectives × ~60 nouns ≈ 3,600 combos — enough for coworker scale.
// Doubles as a profanity filter (nothing gross in here).

import { uniqueNamesGenerator } from 'unique-names-generator'

export const adjectives = [
  'abstract',
  'ancient',
  'angry',
  'azure',
  'blobby',
  'blurry',
  'bold',
  'broken',
  'chonky',
  'chunky',
  'classic',
  'cloudy',
  'cobalt',
  'cosmic',
  'crispy',
  'crooked',
  'crusty',
  'curvy',
  'damp',
  'dark',
  'digital',
  'dripping',
  'dusty',
  'epic',
  'feral',
  'fishy',
  'flat',
  'fluffy',
  'foggy',
  'fragile',
  'funky',
  'fuzzy',
  'gloomy',
  'golden',
  'greasy',
  'gritty',
  'haunted',
  'hazy',
  'hollow',
  'icy',
  'itchy',
  'janky',
  'jazzy',
  'jolly',
  'juicy',
  'lumpy',
  'mad',
  'melted',
  'messy',
  'moody',
  'mossy',
  'muddy',
  'mystic',
  'neon',
  'noisy',
  'odd',
  'pastel',
  'pixel',
  'pointy',
  'purple',
  'retro',
  'round',
  'rusty',
]

export const nouns = [
  'artist',
  'blob',
  'brush',
  'bucket',
  'canvas',
  'chalk',
  'chisel',
  'collage',
  'color',
  'crayon',
  'cubist',
  'doodle',
  'drip',
  'easel',
  'eraser',
  'exhibit',
  'fresco',
  'gallery',
  'glaze',
  'gouache',
  'graffiti',
  'impasto',
  'ink',
  'kiln',
  'layer',
  'lino',
  'mallet',
  'maquette',
  'marker',
  'matte',
  'medium',
  'mural',
  'museum',
  'oil',
  'palette',
  'panel',
  'pastel',
  'patron',
  'pencil',
  'pigment',
  'pixel',
  'plaster',
  'portrait',
  'poster',
  'primer',
  'print',
  'resin',
  'sculptor',
  'sketch',
  'smear',
  'smudge',
  'spatula',
  'spray',
  'stencil',
  'stipple',
  'stroke',
  'study',
  'tempera',
  'texture',
  'tint',
  'varnish',
  'wash',
  'watercolor',
]

// A random adjective-noun pair, e.g. "feral-crayon". Shared by the room-code
// generator (Entry) and the random-name fallback (App / Lobby).
export function wordPair(): string {
  return uniqueNamesGenerator({
    dictionaries: [adjectives, nouns],
    separator: '-',
    length: 2,
    style: 'lowerCase',
  })
}
