// Room codes are generated by `wordPair()` and validated by `isRoomCode()` (#66). The two
// must never disagree: a dictionary word the regex rejects would make ~1-in-60 created rooms
// unopenable, with no failing test and no obvious symptom. These pin that coupling.

import { describe, expect, it } from 'vitest'
import { adjectives, isRoomCode, nouns, wordPair } from '../src/lib/content/words'

describe('isRoomCode', () => {
  it('accepts a well-formed {word}-{word} code, including every code wordPair emits', () => {
    expect(isRoomCode('feral-crayon')).toBe(true)
    for (let i = 0; i < 200; i++)
      expect(isRoomCode(wordPair())).toBe(true)
  })

  it('rejects anything that is not two lowercase words and a single hyphen', () => {
    for (const bad of ['', 'feral', 'feral crayon', 'feral-crayon-extra', 'feral--crayon', 'Feral-Crayon', 'a_b', 'a1-b2'])
      expect(isRoomCode(bad)).toBe(false)
  })

  it('is kept honest by the word lists: every entry is lowercase letters only', () => {
    for (const w of [...adjectives, ...nouns])
      expect(w).toMatch(/^[a-z]+$/)
  })
})
